module.exports = [
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 1,
    fields: {
      ingredient: 15,
      synonymous_name_NL_S: "oude kaas",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "old cheese",
      synonymous_name_EN_P: "old cheeses",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 2,
    fields: {
      ingredient: 27,
      synonymous_name_NL_S: "jus d'orange",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "jus d'orange",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 3,
    fields: {
      ingredient: 70,
      synonymous_name_NL_S: "ei",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "egg",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 4,
    fields: {
      ingredient: 78,
      synonymous_name_NL_S: "kookroom",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "cooking cream",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 5,
    fields: {
      ingredient: 78,
      synonymous_name_NL_S: "room",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "cream",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 6,
    fields: {
      ingredient: 13,
      synonymous_name_NL_S: "zoete sojasaus",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "sweet soy sauce",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 7,
    fields: {
      ingredient: 90,
      synonymous_name_NL_S: "zoute sojasaus",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "salty soy saus",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 8,
    fields: {
      ingredient: 93,
      synonymous_name_NL_S: "haricots verts",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "french bean",
      synonymous_name_EN_P: "french beans",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 9,
    fields: {
      ingredient: 132,
      synonymous_name_NL_S: "kurkuma",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 10,
    fields: {
      ingredient: 157,
      synonymous_name_NL_S: "bernagie",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 11,
    fields: {
      ingredient: 253,
      synonymous_name_NL_S: "klapstuk",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 12,
    fields: {
      ingredient: 240,
      synonymous_name_NL_S: "riblap",
      synonymous_name_NL_P: "riblappen",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 13,
    fields: {
      ingredient: 240,
      synonymous_name_NL_S: "ribstuk",
      synonymous_name_NL_P: "ribstukken",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 14,
    fields: {
      ingredient: 240,
      synonymous_name_NL_S: "rollade",
      synonymous_name_NL_P: "rollades",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 15,
    fields: {
      ingredient: 240,
      synonymous_name_NL_S: "stooflap",
      synonymous_name_NL_P: "stooflappen",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 16,
    fields: {
      ingredient: 266,
      synonymous_name_NL_S: "spaakhammetje",
      synonymous_name_NL_P: "spaakhammetjes",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 17,
    fields: {
      ingredient: 275,
      synonymous_name_NL_S: "frisée",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 18,
    fields: {
      ingredient: 277,
      synonymous_name_NL_S: "radicchio",
      synonymous_name_NL_P: "",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 19,
    fields: {
      ingredient: 174,
      synonymous_name_NL_S: "erwt",
      synonymous_name_NL_P: "erwten",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 20,
    fields: {
      ingredient: 279,
      synonymous_name_NL_S: "limaboon",
      synonymous_name_NL_P: "limabonen",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 21,
    fields: {
      ingredient: 280,
      synonymous_name_NL_S: "topinamboer",
      synonymous_name_NL_P: "topinamboeren",
      synonymous_name_EN_S: "",
      synonymous_name_EN_P: "",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 22,
    fields: {
      ingredient: 103,
      synonymous_name_NL_S: "stervrucht",
      synonymous_name_NL_P: "stervruchten",
      synonymous_name_EN_S: "star fruit",
      synonymous_name_EN_P: "star fruits",
    },
  },
  {
    model: "ingredientserver.ingredientsynonym",
    pk: 23,
    fields: {
      ingredient: 304,
      synonymous_name_NL_S: "curuba",
      synonymous_name_NL_P: "curuba's",
      synonymous_name_EN_S: "curuba",
      synonymous_name_EN_P: "curuba",
    },
  },
];
